### ISSUE TITLE
How about supporting StackExchange.Redis library in version 2.0.x?

### ISSUE THREAD

**Issue by alex-mazzariol** [KidFashion/redlock-cs#5]
It seems to require some changes to the code; are there any plans on upgrading the dependency?

**Comment by KidFashion** [comment]
In case you are still interested I've released version 2.0.8

Code has been ported to .NET Standard (therefore is usable both on .NET Core and .NET Framework) and now depends on StackExchange.Redis 2.0.x (currently >= 2.0.519)

**Comment by alex-mazzariol** [comment]
Yes I'm still interested, and thank you very much for this!
