### ISSUE TITLE
Use interface IConnectionMultiplexer instead of instance class

### ISSUE THREAD

**Issue by pantosha** [KidFashion/redlock-cs#7]
The `Redlock` constructor takes an array of `ConnectionMultiplexer` classes.
`ConnectionMultiplexer` has an interface `IConnectionMultiplexer` that is more suitable for development.

It's reasonable to replace `ConnectionMultiplexer` class with `IConnectionMultiplexer` interface in constructor.

**Comment by KidFashion** [comment]
Make a lot of sense, 

Thank you!
